In [1]:
import numpy as np

The Numpy array - an *n* dimensional object, is the central object of the Numpy package

1D array = Vector
2D array = Matrix
3D array = Tensor (set of Matrices)
- there can be arrays of 4+ dimensions too

- all items in array have to be of same data type. For an array with different data types, use pandas DataFrame, or Numpy's record array



In [2]:
# you can manually create array with array() function. 2D array in this case
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [3]:
# arange() function great for creating vectors easily
# in this case, created vector with values 1 up to (but not including) 10
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# zeros() takes a tuple of the array's dimensions as an argument.
# fills the array with zeros
np.zeros((5,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [9]:
# works with ones too
np.ones((7,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [14]:
# full() creates an array repeating a fixed value
np.full((4,3), 9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [16]:
# use .shape to find shape of an array
myarray = np.ones((3,5,4))
myarray.shape

(3, 5, 4)

In [17]:
# example of  3D array (tensor)
myarray

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [19]:
# you can change shape of array as long as total number of items is the same
myarray.reshape(20,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
# you can use -1 to infer one of the dimensions (but array has to be possible)
myarray.reshape(10, -1)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])